name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: cat /etc/alpine-release
        shell: alpine.sh {0}
      - run: apk update
      - run: apk upgrade
      - run: apk add --update alpine-sdk linux-headers git zlib-dev openssl-dev gperf php cmake
      - run: git clone https://github.com/tdlib/td.git
      - run: ls -l
